### ISSUE TITLE
tokenSecret returns an empty object

### ISSUE THREAD

**Issue by mcmxc** [fuwaneko/passport-trello#2]
Hey there! Thanks for this package! I'm having an issue though - tokenSecret happends to be an empty object, when I'm trying to log it out. Here is my Strategy configuration:

```
import passport from 'passport';
import { Strategy as TrelloStrategy } from 'passport-trello';

export default () => {
  passport.use(new TrelloStrategy({
    consumerKey: process.env.TRELLO_CONSUMER_KEY,
    consumerSecret: process.env.TRELLO_CONSUMER_SECRET,
    callbackURL: 'http://localhost:3000/auth/trello/callback',
    trelloParams: {
      scope: 'read',
      name: 'Common Feed',
      expiration: '1hour'
    }
  }, (req, token, tokenSecret, profile, done) => {
      let user = {};
      user.token = token;
      user.tokenSecret = tokenSecret;
      user.profile = profile;
      user.req = req;
      done(null, user);
  }));
}

```

and the second question - what `req` stands for in this function? I figured out it returns a string, what is that string ? Thank You!

**Comment by fuwaneko** [comment]
Maybe something has changed on Trello side or with how Passport handles custom strategies. I can look into things when I have time, but if you can't wait you can make pull request, I'll gladly accept it.

**Comment by mcmxc** [comment]
Thanks for the answer. Maybe you also have something to say about my second question? It is strange, but `req` returns a string, that looks much like a `token`, but twice longer than that. Maybe that `req` string happens to be a secretToken? Any thoughts about that? Thanks

**Comment by mcmxc** [comment]
Yup, that `req` is exactly the user token (tokenSecret) which is needed to access trello API
