### ISSUE TITLE
CORB issue in auth url

### ISSUE THREAD

**Issue by thamera** [fuwaneko/passport-trello#3]
Does anyone have this working.  I am getting the userAuthorizationUrl passed back to my app but it has a cross-origin read blocking (CROB) error.  looks like the return is text.html but maybe the header in the request specified a json content type.  Can't seem to find where this is happening.
![image](https://user-images.githubusercontent.com/5296746/57985646-da816a00-7a1f-11e9-8c2d-7eebac5e7e7b.png)

**Comment by fuwaneko** [comment]
I assume you're trying to use this library from the browser? It is intended for server-side usage.
